=== eltoraz/alchemy/alchemy/assets/potions.xsd
<xs:schema elementFormDefault="qualified"
           xmlns="https://eltoraz.github.io/alchemy"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="potions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="potion" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="description"/>
                            <xs:element name="effects">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="effect">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="type" use="required"/>
                                                        <xs:attribute type="xs:float" name="magnitude" use="optional"/>
                                                        <sd:attribute type="xs:float" name="mult" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="recipe">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="element" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="type" use="required"/>
                                                        <xs:attribute type="xs:float" name="min" use="optional"/>
                                                        <xs:attribute type="xs:float" name="max" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== eltoraz/alchemy/alchemy/assets/potions.xml
<?xml version="1.0"?>
<potions xmlns="https://eltoraz.github.io/alchemy"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://eltoraz.github.io/alchemy potions.xsd">
    <potion name="healing potion">
        <description>just your average vitality-restoring potion</description>
        <effects>
            <effect>
                <type>restore_health</type>
                <magnitude>25.0</magnitude>
            </effect>
        </effects>
        <recipe>
            <ingredient>
                <element>
                    <type>Water</type>
                    <min>10.0</min>
                    <max>12.0</max>
                </element>
            </ingredient>
            <ingredient>
                <element>
                    <type>Spirit</type>
                    <min>0.1</min>
                    <max>1.0</max>
                </element>
            </ingredient>
        </recipe>
    </potion>
    <potion name="haste salve">
        <description>apply to ankles or equivalent</description>
        <effects>
            <effect>
                <type>haste</type>
                <magnitude>2.0</magnitude>
            </effect>
        </effects>
        <recipe>
            <ingredient>
                <element>
                    <type>Fire</type>
                    <min>5.0</min>
                    <max>10.0</max>
                </element>
            </ingredient>
            <ingredient>
                <element>
                    <type>Storm</type>
                    <min>6.0</min>
                    <max>8.0</max>
                </element>
            </ingredient>
        </recipe>
    </potion>
</potions>
